### ISSUE TITLE
More candidates

### ISSUE THREAD

**Issue by jhass** [veelenga/awesome-crystal#14]
I'm just going to list a few more projects, add what you like.

* https://github.com/ysbaddaden/artanis
* https://github.com/spalger/crystal-mime
* https://github.com/romeroadrian/nes.cr
* https://github.com/benoist/msgpack-crystal
* https://github.com/manastech/conan
* https://github.com/porras/mock
* https://github.com/ggiraldez/crystal-pong

**Comment by veelenga** [comment]
Thanks a lot for sharing. I have added most all. Unfortunately, we can't add some items, because they do not meet the general idea of `awesome-crystal`:

> The goal is to have projects mostly stable and useful for users.

You are welcome to add a new entry (or open an issue) if you have another useful projects.
