### ISSUE TITLE
Move tensorflow.cr to Machine learning

### ISSUE THREAD

**Issue by bararchy** [veelenga/awesome-crystal#179]
Hi, 
I think that because there is a Machine Learning section, TensorFlow should be there, it's a very high profile ML tool and would make the section feel more full, while the c bindings list is already quite large

tensorflow.cr - Bindings for TensorFlow

**Comment by bararchy** [comment]
If were on the Subject:

1) https://github.com/pbrusco/crystal-learn  
2) https://github.com/mathieulaporte/machine  

Should be moved too ;)

**Comment by veelenga** [comment]
Thank you for letting know 👍
