### ISSUE TITLE
website is down, domain expired

### ISSUE THREAD

**Issue by fridgerator** [veelenga/awesome-crystal#189]

**Comment by veelenga** [comment]
Yes, i didn't plan to continue to use it and plan to remove a [CNAME file](https://github.com/veelenga/awesome-crystal/blob/gh-pages/CNAME) from the gh-pages branch.
IMO repository's [landing page on github](https://github.com/veelenga/awesome-crystal) is a better alternative for this.

**Comment by fridgerator** [comment]
ok, sounds good 👍
