### ISSUE TITLE
The domain expired - http://awesome-crystal.com/

### ISSUE THREAD

**Issue by tzekid** [veelenga/awesome-crystal#191]
![20170730_201836](https://user-images.githubusercontent.com/6037154/28755914-c2022030-7564-11e7-99c3-e9b1544b1140.jpg)

**Comment by veelenga** [comment]
Duplicated of #189

Unfortunately, I don't plan to use this domain any more.
The old site you can now find here: https://veelenga.github.io/awesome-crystal
