### ISSUE TITLE
QML bindings for the Crystal language and GUI library

### ISSUE THREAD

**Issue by papilip** [veelenga/awesome-crystal#242]
Hello

We do not have a section to list GUI library solutions.
I just found this link, I suggest you to start

https://github.com/Papierkorb/qt5.cr

Have a nice day, Papilip

**Comment by hugoabonizio** [comment]
Hi @papilip!

Would you mind opening a PR including a `GUI` section and this library to it?

Thanks :smile:

**Comment by papilip** [comment]
Hi @hugoabonizio 

As you suggest, i have make this PR #243 

Thank for this idea
