### ISSUE TITLE
Include stdlib features?

### ISSUE THREAD

**Issue by straight-shoota** [veelenga/awesome-crystal#258]
Currently libraries that come with the Crystal stdlib are not included. But there are already some great features bundled with Crystal that shouldn't be missing here. For example, the section about *template engines* doesn't mention ECR - if you're looking for a template engine in Crystal, that should be on the table.
Now, I wouldn't want to add everything the stdlib offers, but some more libraries should be listed. Not just to give a more complete overview, but for many use cases the implementations from stdlib are a really strong option. Especially regarding no additional dependencies.

Some examples:

* *Cli Builders*: `OptionParser`
* *Configuration* (or better call it *Data Formats*): `INI, YAML, JSON, CSV`
* *HTML/XML Parsing*: `XML`
* *HTTP*: `HTTP::Client`
* *Logging and monitoring*: `Logger`
* *Template Engine*: `ECR`
* *Testing*: `Spec`
* *Web servers*: `HTTP::Server`

(I wouldn't add `Markdown` because it is very minimal and IMHO not suitable for general use)

**Comment by veelenga** [comment]
@straight-shoota sounds good. would you like to submit a PR? There we can discuss pros and cons of inclusion each of those.
