### ISSUE TITLE
Add cystalshards

### ISSUE THREAD

**Issue by pyros2097** [veelenga/awesome-crystal#3]
You can get an entire list from crystal shards and maybe you can add that as a resource..
https://crystalshards.herokuapp.com/

**Comment by veelenga** [comment]
Added to **Services and Apps** group. We can't get an entire list from crystalshards as goal of awesome-crystal is to have stable and useful for community projects. And crystalshards lists all available project on github. But it's a nice resource and could be used to search new awesome projects.

Thanks.
