### ISSUE TITLE
Where to put https://github.com/crystal-loot/exception_page ?

### ISSUE THREAD

**Issue by paulcsmith** [veelenga/awesome-crystal#306]
Hi there!

Just finished up a new lib: https://github.com/crystal-loot/exception_page with help from @faustinoaq!

What section do you think it should go in?

**Comment by veelenga** [comment]
Lets put it into [Framework Components](https://github.com/veelenga/awesome-crystal#framework-components).

**Comment by paulcsmith** [comment]
Ah yes! I didn't see that. Looks perfect :) And thank you!
