### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by psikoz** [veelenga/awesome-crystal#312]
Hey @veelenga , I think that I designed the most appropriate logotype for the your repo. I combined awesome and crystal. so the properties of this repo became more prominent. WDYT? If you like one of these, I will send you a pr.

![ac](https://user-images.githubusercontent.com/40601249/43193211-0cbee13a-9008-11e8-9379-65789f21d0ec.jpg)

**Comment by veelenga** [comment]
Very cool. Maybe this one:

![image](https://user-images.githubusercontent.com/3624712/43195251-23286630-900d-11e8-937a-0e505b4011c1.png)

Let's remove the Crysal logo at the beginning of the Readme and add this one. Thanks a lot

**Comment by psikoz** [comment]
I'm glad you like it :) I forgot to actually add the font variation. If you like these variations / fonts, I will send you all variations. Also, i will update the readme.

![ac](https://user-images.githubusercontent.com/40601249/43203445-e73a821a-9026-11e8-9d4e-5705ab0d2efe.jpg)

**Comment by veelenga** [comment]
That font is just okay.

**Comment by vladfaust** [comment]
Why not putting default glasses into Crystal figure?

**Comment by psikoz** [comment]
I hesitated because of copyright. @vladfaust

**Comment by vladfaust** [comment]
@psikoz as seen on http://awesome.re in the very bottom, the image is under CC0 license, allowing its usage anywhere

**Comment by veelenga** [comment]
@psikoz do you want to try?

**Comment by psikoz** [comment]
ofcourse, how is this?  Also, if you want, i can use awesome font.

![untitled-1](https://user-images.githubusercontent.com/40601249/43218700-d589f042-904d-11e8-9784-9376dcc3c605.jpg)

**Comment by veelenga** [comment]
@psikoz maybe glasses inside a crystal icosahedron is a bit more fun. What do you think?

**Comment by psikoz** [comment]
yes, how is these?

![untitled-1](https://user-images.githubusercontent.com/40601249/43252963-71178ff0-90cc-11e8-8784-41eeb381d7ec.jpg)

**Comment by veelenga** [comment]
@psikoz perfect!

Let's use black&white one and update the PR 👏

**Comment by psikoz** [comment]
Ofcourse, i will send a pr. Do you know the name of the awesome font?  @veelenga , @vladfaust . I searched the font, but I could not find it.  . Because,  I'll write '' awesome-crystal ''

I think it will be better this way. What do you think?

**Comment by vladfaust** [comment]
@psikoz I have no idea which font it is, but you can try to find it @ https://fontsquirrel.com

**Comment by vladfaust** [comment]
Just playing...

![cool-guy](https://user-images.githubusercontent.com/7955682/43259833-522bfcf2-90e0-11e8-82f4-e534d5ef9565.png)
![cool-guy2](https://user-images.githubusercontent.com/7955682/43259834-524bbd94-90e0-11e8-80c8-9dd851f88189.png)

**Comment by veelenga** [comment]
@psikoz let's stick this logo

![image](https://user-images.githubusercontent.com/3624712/43264370-9f67e3d8-90ee-11e8-9b48-ae33d329fd60.png)

Would be cool to have "awesome-crystal" there as it matches the repo name.

**Comment by psikoz** [comment]
I finally found a font that resembles the original font. I will send these variations as pr. What do you say?

![untitled-1](https://user-images.githubusercontent.com/40601249/43326548-d219294e-91c1-11e8-8bea-ae16d2237eed.jpg)

**Comment by veelenga** [comment]
I love it. Looks great.

**Comment by psikoz** [comment]
I updated the pull-request :)
