### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by mamantoha** [veelenga/awesome-crystal#345]
Hi @veelenga.

What do you think about a website for this project?
We can use GitHub Pages for this purpose (see example https://mamantoha.github.io/awesome-crystal and https://github.com/mamantoha/awesome-crystal/tree/gh-pages).
Inspired from https://github.com/markets/awesome-ruby/

**Comment by veelenga** [comment]
We already had one in gh-pages branch. Looked very similar to you example, but with a black theme. But i have removed it in favor of http://awesomelists.top/#/repos/veelenga/awesome-crystal

**Comment by mamantoha** [comment]
Oh. Did not notice that :)
Close.

**Comment by veelenga** [comment]
Thanks for the suggestion.
