### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by vladfaust** [veelenga/awesome-crystal#346]
Hello. Recently I've run a script to find shards which cannot be compiled with the latest Crystal (0.26.1):

<details>
<summary>script.cr</summary>

```crystal
# It's not ideal, but it works
errored = {
  "git_clone":      [] of String,
  "shards_install": [] of String,
  "spec":           [] of String,
}

File.read_lines("./README.md").each do |line|
  if line =~ %r{\* \[(?<name>[\w\.]+)]\((?<url>[\w\.:/]+)\) - .+}
    puts "Checking #{$~["name"]} (#{$~["url"]})..."

    puts `git clone #{$~["url"]}.git #{$~["name"]}`

    unless $?.exit_status == 0
      errored["git_clone"] << $~["url"]
      next
    end

    puts `cd #{$~["name"]} && shards install`

    unless $?.exit_status == 0
      errored["shards_install"] << $~["url"]
      next
    end

    puts `cd #{$~["name"]} && crystal spec`

    unless $?.exit_status == 0
      errored["spec"] << $~["url"]
      next
    end

    puts "Checked #{$~["name"]} ✔️"
  end
end

pp! errored
```
</details>

---

I got **101** results. Then I filtered C bindings and shards with complex specs (involving third parties). Then I manually created **46** issues in those shard repositories. Some of them are now building nicely (✔️) , others are confirmed to be abandoned (✖️), but more than a half of the authors ignored the issue.

There is a spreadsheet where I track everything: https://docs.google.com/spreadsheets/d/1s78Q70PubWtprlsvaRvvWpQVcbjYwUXdbzeoVMAxZqQ/edit?usp=sharing

I'll create a PR to remove confirmed abandoned shards. I'll comment under this post to mention ones who've ignored the initial issue to give them another chance to reply.

I also would like to create a separate section for abandoned shards which could be useful to the community (like some algorithms) and mention something like "you could revive this shard and we'll move it back to the active section".

**Comment by azah** [comment]
If you create a section like that, or one for projects looking for new maintainers, you can add mine to it.
* [dotacr](https://github.com/azah/dotacr) - just needs to be updated to the latest Crystal version. It's a simple project; one just needs a [Steam Web API Key](https://steamcommunity.com/dev). As far as I can tell nobody actually has used this so I don't care to maintain it.

**Comment by vladfaust** [comment]
Nice reply, @azah. I think there are other shards which are in a situation like yours - it almost works. To you and all same authors I propose to update their shards to the latest Crystal **and** setup cron (daily or weekly) builds on their CI providers.

**Comment by vladfaust** [comment]
I also would like to ping @watzon for non-working https://watzon.me/projects/json-to-crystal and @faustinoaq for forever-maintained https://shards.rocks/

**Comment by arktisklada** [comment]
Thanks for the heads up!  will look into updating the project

**Comment by veelenga** [comment]
Thanks, @vladfaust for doing this. I have done such cleanups a couple of times and can say it requires some effort and takes time :)

**Comment by faustinoaq** [comment]
@vladfaust Thanks for mention me, I'll update my shards :+1:  :)

I think shards.rocks still requires a big refactoring :sweat_smile:

**Comment by dorkrawk** [comment]
@vladfaust Thanks for the mention. I'll update Moola and make sure it compiles, it should be pretty simple.

**Comment by jeromegn** [comment]
@vladfaust jeromegn/bson.cr#2 should be fixed now, travis just passed.

**Comment by dorkrawk** [comment]
@vladfaust So I just upgraded to Crystal 0.26.1 and then ran the test suite and compiled Moola ( https://github.com/dorkrawk/moola ) and everything seemed to work just fine.

**Comment by vladfaust** [comment]
@dorkrawk um the issuing project of yours is https://github.com/dorkrawk/grey_matter/issues/6 :confused:

**Comment by dorkrawk** [comment]
@vladfaust Oh yea... that one is a bit more neglected...

**Comment by watzon** [comment]
@vladfaust unfortunately money has been tight recently and I haven't been able to afford to keep my server up. As soon as I'm able I will have the project back up.

**Comment by porras** [comment]
Thanks for the heads up @vladfaust. I fixed the issues in https://github.com/porras/crul/pull/26, which I'll merge today as soon as I do a bit of manual testing, and think what to do with the bash completion situation.

**Comment by vladfaust** [comment]
So, a long time passed by, and it's time to reveal the banhammer *demonically laughs*

However, I'm really conserned about "Abandoned but useful" section and I don't want to hurt anyone with my willing decision and also I haven't tested all the shards, so I really don't know which ones are really useful...

**Comment by veelenga** [comment]
@vladfaust I don't think we need that section. Unfortunately, if the shard doesn't compile/abandoned, we have to remove it from the list. There are other places where it can be found for learning purpose: github, crystalshards

**Comment by lucaong** [comment]
@vladfaust I managed to update https://github.com/lucaong/immutable to be compatible with latest Crystal `v0.26.1`
