### ISSUE TITLE
Require daily/weekly builds against stable Crystal in .CONTRIBUTING

### ISSUE THREAD

**Issue by vladfaust** [veelenga/awesome-crystal#347]
I propose that to make sure authors react quickly when their shard begins to fails against the fresh Crystal version. On Travis CI it could be checked in build history.

**Comment by veelenga** [comment]
Let's do it. Open a PR please.

**Comment by Schniz** [comment]
Sounds awesome. Can you add a reference `.travis.yml` file so shard maintainers can just copy and paste?

**Comment by vladfaust** [comment]
Indeed. Sorry for delay, got some busy week
