### ISSUE TITLE
Should I add cookbook to the list?

### ISSUE THREAD

**Issue by vjdhama** [veelenga/awesome-crystal#39]
I am working on a cookbook for installing crystal using chef. Should I add that to the list?
The cookbook is written in Ruby, hence the confusion.

**Comment by veelenga** [comment]
@vjdhama Sure, you can add it. The main goal of the project is to have awesome Crystal libraries, tools, frameworks, software and everything around it. Be free to add new subsection to [Tools](https://github.com/veelenga/awesome-crystal#tools) ("DevOps" or "Configuration Management" should be good).

**Comment by vjdhama** [comment]
@veelenga Thanks. I'll add it then.
