### ISSUE TITLE
Broken spec

### ISSUE THREAD

**Issue by sanata-** [veelenga/awesome-crystal#43]
When fork and run specs, get
Failures:

  1) List of Crystal Awesomeness has alphabetical case insensitive order
     Failure/Error: awesome.should eq sorted[i]

       expected: "Community"
            got: "Configuration"

     # ./spec/readme_spec.cr:40

Finished in 10.82 milliseconds
4 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec ./spec/readme_spec.cr:36 # List of Crystal Awesomeness has alphabetical case insensitive order

**Comment by veelenga** [comment]
@sanata- Master could be incompatible with older versions of Crystal. Be sure you are using latest one:

```sh
awesome-crystal git:master ❯ crystal -v                                                                                                                                            ✭
Crystal 0.14.2 (Wed Mar 23 01:14:25 UTC 2016)
awesome-crystal git:master ❯ crystal spec                                                                                                                                          ✭
....

Finished in 8.34 milliseconds
4 examples, 0 failures, 0 errors, 0 pending
```

**Comment by sanata-** [comment]
Thanks @veelenga!
Everything work 👍

**Comment by veelenga** [comment]
@sanata- Glad to hear :+1:
