### ISSUE TITLE
Simulation: Conways Game of Life

### ISSUE THREAD

**Issue by KieranP** [veelenga/awesome-crystal#459]
I wrote this if you want to include it in the list: https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/crystal

**Comment by veelenga** [comment]
Hey. Thanks for the suggestion. Please be free to submit a PR if your implementation matches these contribution guidelines:

https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md
