### ISSUE TITLE
Evaluation of `glove` library

### ISSUE THREAD

**Issue by saveriomiroddi** [veelenga/awesome-crystal#467]
I was checking out the game development libraries, and I came across the `glove` library.

The guidelines for project introduction give a relatively clear threshold for projects inclusion, that is, maturity.

The `glove` project however, discourages itself using it in projects (["Do not use this for your own projects"](https://github.com/ddfreyne/glove)), and the activity is sporadic (a bit more than a commit per month [in the last year](https://github.com/ddfreyne/glove/commits/master)), so I wonder if it should be kept in the list, or not.

**Comment by Qard** [comment]
It's more a warning not to expect support than anything. It's a hobby project and should be treated as such. I'm one of the contributors and use it for some hobby projects of mine.

**Comment by veelenga** [comment]
Thanks for pointing out.

It is totally fine to have unfinished projects on the list. Even Crystal itself is still not production-ready.
