### ISSUE TITLE
A CLI tool to quickly create Kubernetes clusters in Hetzner Cloud

### ISSUE THREAD

**Issue by vitobotta** [veelenga/awesome-crystal#597]
Hi! I was wondering if we could add this tool to the list? It's a tool that I built (originally in Ruby, then rewritten from scratch in Crystal) to create and manage K8s clusters in Hetzner Cloud, a provider with locations in Germany, Finland and USA. What do you think?

Here's the repo for reference: https://github.com/vitobotta/hetzner-k3s

**Comment by Blacksmoke16** [comment]
Checkout https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md and feel free to make a PR when/if it meets all the requirements.
