### ISSUE TITLE
Several useful shards

### ISSUE THREAD

**Issue by zw963** [veelenga/awesome-crystal#605]
Do you consider add following shards into awesome-crystal?

## https://github.com/crystal-china/procodile_cr

Port from same name ruby gem,  like [crank](https://github.com/arktisklada/crank), but more powerful.
Although there is still a [issue](https://forum.crystal-lang.org/t/need-document-for-how-porting-io-select-in-ruby-crystal/5374/1) need to be solve

## https://github.com/crystal-china/hashr

A really tiny shards used for test json response only. Inspired by same name ruby gem. https://github.com/svenfuchs/hashr

## https://github.com/crystal-china/port_ruby_to_crystal

Porting Ruby code into Crystal easier.

there are others shards in [crystal-china org](https://github.com/crystal-china), and I will add more shards to it.

Thanks.

**Comment by veelenga** [comment]
We would be happy to accept new additions to the list if they do not break the [Contribution guidelines](https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md). 

Would you like opening PRs to contribute?
