### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [veelenga/awesome-crystal#619]
Hi, I found some broken hyperlinks:

- [ ] https://crystalshards.org (file: README.md, error: ECONNRESET)
- [ ] https://www.w3.org/TR/2009/WD-eventsource-20090421 (file: README.md, status code: 404)
- [ ] https://faastruby.io (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://crystalshards.herokuapp.com/ (file: README.md, status code: 404)
- [ ] http://www.crystular.org (file: README.md, status code: 503)

**Comment by veelenga** [comment]
Thanks for reporting. Would you like to create a PR to remove those?
