### ISSUE TITLE
number of github stars, last date committed

### ISSUE THREAD

**Issue by rdp** [veelenga/awesome-crystal#81]
Would be nice if it could include these somehow... :|

**Comment by veelenga** [comment]
Somehow we can extend (or reimplement) http://awesome-crystal.com/ and have this information,  but to be honest, at the moment, i don't have plans and time for this. Probably what you are looking for is:

* http://crystalshards.herokuapp.com/
* http://crystalshards.xyz/

For now i will close this issue and we may think about it in future again. Of course if you, or somebody else are super inspired and could submit a PR for this, I would be happy to review and merge it. Thank you.

**Comment by rdp** [comment]
Perfect thanks.
