### ISSUE TITLE
crystalshards

### ISSUE THREAD

**Issue by miketheman** [veelenga/awesome-crystal#84]
https://crystalshards.herokuapp.com/ (from https://github.com/zamith/crystalshards )
vs
http://crystalshards.xyz/ ~~(unknown source)~~ (from https://github.com/f/crystalshards)

Also referenced in https://github.com/veelenga/awesome-crystal/issues/81#issuecomment-250372885

Should we keep one or the other? Add the .xyz one?

**Comment by askn** [comment]
http://crystalshards.xyz source is here https://github.com/f/crystalshards

cc: @f

**Comment by veelenga** [comment]
To be honest, i thought that .xyz one is already in the list :blush:. I think it is better to have both in the list, both work well and have some users.

Thanks, guys.
